version: '3'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3450:3450"
    depends_on:
      - backend
      - database

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    depends_on:
      - database
    env_file:
      - ./.env

  database:
    image: mongo
    ports:
      - "27017:27017"
